export default {
  index: 'Introduction',
  'getting-started': 'Getting Started',
  'project-setup': 'Project Setup',
  configuration: 'Configuration',
  'results-and-errors': 'Results & Errors',
  auth: 'Authentication',
  database: 'Database',
  storage: 'Storage',
  realtime: 'Realtime',
  functions: 'Edge Functions',
  paging: 'Pagination',
  encryption: 'End-to-End Encryption',
  'vector-search': 'Vector Search',
  platforms: 'Platforms',
  github_link: {
    title: 'GitHub',
    type: 'page',
    href: 'https://github.com/AndroidPoet/supabase-kmp',
    newWindow: true,
  },
}
